site_name: Something
nav:
  - Home: index.md
  - About: about.md
  - Archive: archive.md
theme: 
    name: readthedocs
    custom_dir: theme_overrides
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+' # Optional: customize how words are split