site_name: Something
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md
  - Tags: tags.md
theme:
    name: material
    features:
        - navigation.indexes
plugins:
  - search:
      pipeline:
        - stemmer
        - trimmer
  - tags
  - blog:
      blog_dir: blog
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Java 26